[pytest]
pythonpath = .
testpaths = tests
filterwarnings =
    ignore:.*BaseCommand.*:DeprecationWarning:typer\.completion
    ignore:.*__version__ attribute.*:DeprecationWarning:typer\._compat_utils
